; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
lib_deps = 
	AccelStepper
	stm32duino/STM32duino FreeRTOS@^10.3.3
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D CONFIG_ARDUINO_USB_CDC_ON_BOOT=1
	-D USBCON
	-D USBD_VID=0x0483
	-D USBD_PID=0x5740
	-D HAL_PCD_MODULE_ENABLED
	-D USBD_USE_CDC
	-D configUSE_PREEMPTION=1
	-D configUSE_IDLE_HOOK=0
	-D configUSE_TICK_HOOK=0
	-D configCPU_CLOCK_HZ=72000000
	-D configTICK_RATE_HZ=1000
	-D configMAX_PRIORITIES=5
	-D configMINIMAL_STACK_SIZE=128
	-D configTOTAL_HEAP_SIZE=10240
